// THIS FILE IS GENERATED - DO NOT MODIFY
/**
 *  Autogenerated by current cli tool
 */
export const BUILD_FRAMEWORK_CLI_NAME = 'tnp';
/**
 *  This value can be change in taon.jsonc (appId)
 */
export const APP_ID = 'com.domain.example.isomorphic-lib-v19';
/**
 *  Autogenerated by current cli tool
 */
export const BUILD_BASE_HREF = '';
/**
 *  This value can be change in taon.jsonc (overrideNpmName)
 */
export const PROJECT_NPM_NAME = 'isomorphic-lib-v19';
/**
 *  Autogenerated by current cli tool. Use *tnp release* to bump version.
 */
export const CURRENT_PACKAGE_VERSION = '16.0.0';
// THIS FILE IS GENERATED - DO NOT MODIFY
      