// THIS FILE IS GENERATED - DO NOT MODIFY
export const BUILD_FRAMEWORK_CLI_NAME = 'tnp';
export const PROJECT_NPM_NAME = 'isomorphic-lib-v19';
export const CURRENT_PACKAGE_VERSION = '16.0.0';
// THIS FILE IS GENERATED - DO NOT MODIFY
      