// THIS FILE IS GENERATED - DO NOT MODIFY
export const BUILD_FRAMEWORK_CLI_NAME = 'tnp';
export const PROJECT_NPM_NAME = 'taon';
export const CURRENT_PACKAGE_VERSION = '19.0.30';
// THIS FILE IS GENERATED - DO NOT MODIFY
      