// THIS FILE IS GENERATED - DO NOT MODIFY
/**
 *  Autogenerated by current cli tool
 */
export const BUILD_FRAMEWORK_CLI_NAME = 'tnp';
/**
 *  This value can be change in taon.jsonc (appId)
 */
export const APP_ID = 'dev.taon.app';
/**
 *  Autogenerated by current cli tool
 */
export const BUILD_BASE_HREF = '';
/**
 *  This value can be change in taon.jsonc (overrideNpmName)
 */
export const PROJECT_NPM_NAME = 'taon';
/**
 * Taon version from you project taon.json
 */
export const CURRENT_PACKAGE_TAON_VERSION = 'v21';
/**
 *  Autogenerated by current cli tool. Use *tnp release* to bump version.
 */
export const CURRENT_PACKAGE_VERSION = '21.0.134';

export namespace TAON_CLOUDFLARE_WORKERS_URLS {
	export const KvWorkerTaonCustomC4327 = 'https://kv-worker-taon-custom-c4327.undefined.workers.dev';
}

// THIS FILE IS GENERATED - DO NOT MODIFY
      