services:
  angular-app-node:
    container_name: angular-app-node
    build:
      context: ./angular-app-node
      dockerfile: ./Dockerfile
    ports:
      - "${FRONTEND_NORMAL_APP_PORT_1}:80"
    environment:
      HOST_BACKEND_PORT_1: "${HOST_BACKEND_PORT_1}"
      HOST_URL_1: "${HOST_URL_1}"
      FRONTEND_HOST_URL_1: "${FRONTEND_HOST_URL_1}"
      FRONTEND_NORMAL_APP_PORT_1: "${FRONTEND_NORMAL_APP_PORT_1}"
    networks:
      - traefik-net
  # - shared_net
  # - isomorphic-lib-v19-app-network

  backend-app-node:
    container_name: backend-app-node
    build:
      context: ./backend-app-node
      dockerfile: ./Dockerfile
    ports:
      - "${HOST_BACKEND_PORT_1}:${HOST_BACKEND_PORT_1}"
    environment:
      HOST_BACKEND_PORT_1: "${HOST_BACKEND_PORT_1}"
      HOST_URL_1: "${HOST_URL_1}"
      FRONTEND_HOST_URL_1: "${FRONTEND_HOST_URL_1}"
      FRONTEND_NORMAL_APP_PORT_1: "${FRONTEND_NORMAL_APP_PORT_1}"
    networks:
      - traefik-net
# - shared_net
# - isomorphic-lib-v19-app-network

# networks:
#   isomorphic-lib-v19-app-network:
#     driver: bridge

# networks:
#   shared_net:
#     external: true


networks:
  traefik-net:
    external: true
