version: '3.9'

services:
  angular-app-node:
    container_name: angular-app-node
    build:
      context: ./angular-app-node
      dockerfile: .Dockerfile
    ports:
      - "${HOST_URL_1}:80"
    networks:
      - isomorphic-lib-v19-app-network

  backend-app-node:
    container_name: backend-app-node
    build:
      context: ./backend-app-node
      dockerfile: .Dockerfile
    ports:
      - "${HOST_BACKEND_PORT_1}:3000"
    environment:
      HOST_URL_1: '${HOST_URL_1}'
      FRONTEND_HOST_URL_1: 'http://localhost:4222'
    networks:
      - isomorphic-lib-v19-app-network

networks:
  isomorphic-lib-v19-app-network:
    driver: bridge
