
//// FILE GENERATED BY TNP /////
import { Morphi } from 'morphi';




export const Controllers: Morphi.Base.Controller<any>[] = [

] as any;

//#region @backend

import { CLASS } from 'typescript-class-helpers';
import { _ } from 'tnp-core'

export function controllers<ADDITIONAL={}>(decoratorsControllers?: ADDITIONAL) {
return _.merge( {

} , decoratorsControllers );
}
//#endregion
