// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
import { isEqual } from 'lodash-es';

import { createWorkerAdapter, app } from '../../../../../../src/app.cloudflare';

export default {
  fetch: createWorkerAdapter(app),
};
