
//// FILE GENERATED BY TNP /////
import { Morphi } from 'morphi';




export const Controllers: Morphi.Base.Controller<any>[] = [

] as any;

//#region @backend

import { CLASS } from 'typescript-class-helpers';
import * as _ from 'lodash'

export function controllers<ADDITIONAL={}>(decoratorsControllers?: ADDITIONAL) {
return _.merge( {

} , decoratorsControllers );
}
//#endregion
